In [48]:
alph = "_ABCDEFGHIJKLMNOPQRSTUVWXYZ"
findfirst(alph,"D")
    
    

In [8]:
print(findfirst(x -> x == 'D' , alph))

5

In [9]:
function vecfromstring(s)
    for i in eachindex(s)
        n = findfirst(x -> x == s[i] , alph)
        

LoadError: syntax: incomplete: "for" at In[9]:2 requires end

In [103]:
function _translate(s)
    n = findfirst(x -> x == s , alph) - 1
    if  n < 3
        n = "00" * string(n,base = 3)
    elseif n < 9
        n = "0" * string(n,base = 3)
    else
        n =  string(n,base = 3)
    end
    n
end
    

_translate (generic function with 1 method)

In [68]:
function translate(s)
    y = ""
    for i in eachindex(s)
        y *= _translate(s[i])
    end
    y
end

translate (generic function with 1 method)

In [52]:
translate("HELLO")

"022012110110120"

In [69]:
function vecfromstring(s)
    v = zeros(Int64, length(s))
    for i in eachindex(s)
        v[i] = parse(Int64, s[i:i])
    end
    v
end
        

vecfromstring (generic function with 1 method)

In [70]:
vecfromstring("01301")

5-element Vector{Int64}:
 0
 1
 3
 0
 1

In [71]:
function vec_from(x) vecfromstring(translate(x)) end
    

vec_from (generic function with 1 method)

In [72]:
vec_from("HELLO")

15-element Vector{Int64}:
 0
 2
 2
 0
 1
 2
 1
 1
 0
 1
 1
 0
 1
 2
 0

In [66]:
vec_from("H")

3-element Vector{Int64}:
 0
 2
 2

In [91]:
function transform(v)
    s = ""
    for i in range(1,length(v), step = 3)
        n = 9*v[i] + 3*v[i+1] + v[i+2]
        s *= alph[n+1]
    end
    s
end

transform (generic function with 1 method)

In [94]:
v = [0,0,0,0,0,0]

6-element Vector{Int64}:
 0
 0
 0
 0
 0
 0

In [95]:
transform(v)

"__"

In [96]:
    alph = "_ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    p = vec_from("THIS_IS_A_TEST_OF_THE_TERNARY_CURIUM_CRYPTOSYSTEM")

137-element Vector{Int64}:
 2
 0
 2
 0
 2
 2
 1
 0
 0
 2
 0
 1
 0
 ⋮
 2
 0
 1
 2
 0
 2
 0
 1
 2
 1
 1
 1

In [97]:
@sprintf

LoadError: LoadError: UndefVarError: `@sprintf` not defined
in expression starting at In[97]:1

In [101]:
using Printf
@sprintf

LoadError: LoadError: MethodError: no method matching var"@sprintf"(::LineNumberNode, ::Module)

Closest candidates are:
  var"@sprintf"(::LineNumberNode, ::Module, ::Any, ::Any...)
   @ Printf /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Printf/src/Printf.jl:960

in expression starting at In[101]:2